CC:=gcc

fopen_test: fopen_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fclose_test: fclose_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fputc_test: fputc_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fputs_test: fputs_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@	

fprintf_test: fprintf_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@	

fgetc_test: fgetc_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fgets_test: fgets_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

stdin_out_err_test: stdin_out_err_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

system_call_test: system_call_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@	